packages:
  - "apps/*"
  - "packages/*"

patchedDependencies:
  next@16.2.10: patches/next@16.2.10.patch

onlyBuiltDependencies:
  - "@whiskeysockets/baileys"
  - esbuild
  - pprof
  - protobufjs
  - electron
  - sharp
  - unrs-resolver
