/** Compatibility re-exports; canonical schemas live in core/association. */
export {
  AssociationActorSchema,
  type AssociationActor,
  AssociationExternalIdentityInputSchema as ExternalIdentityInputSchema,
  type AssociationExternalIdentityInput as ExternalIdentityInput,
  AssociationEnquiryCreateSchema as EnquiryCreateSchema,
  type AssociationEnquiryCreateInput as EnquiryCreateInput,
  AssociationEnquiryStatusSchema as EnquiryStatusSchema,
  type AssociationEnquiryStatus as EnquiryStatus,
  AssociationEnquiryUpdateSchema as EnquiryUpdateSchema,
  type AssociationEnquiryUpdateInput as EnquiryUpdateInput,
  AssociationEnquiryNoteInputSchema as EnquiryNoteInputSchema,
  type AssociationEnquiryNoteInput as EnquiryNoteInput,
  AssociationConsentInputSchema as ConsentInputSchema,
  type AssociationConsentInput as ConsentInput,
  AssociationPlanInputSchema as PlanInputSchema,
  type AssociationPlanInput as PlanInput,
  AssociationMembershipInputSchema as MembershipInputSchema,
  type AssociationMembershipInput as MembershipInput,
  AssociationMembershipUpdateSchema as MembershipUpdateSchema,
  type AssociationMembershipUpdateInput as MembershipUpdateInput,
  AssociationEventInputSchema as EventInputSchema,
  type AssociationEventInput as EventInput,
  AssociationTicketInputSchema as TicketInputSchema,
  type AssociationTicketInput as TicketInput,
  AssociationOrderAttendeeSchema as OrderAttendeeSchema,
  AssociationOrderLineInputSchema as OrderLineInputSchema,
  AssociationOrderCreateSchema as OrderCreateSchema,
  type AssociationOrderCreateInput as OrderCreateInput,
  AssociationOrderStatusSchema as OrderStatusSchema,
  type AssociationOrderStatus as OrderStatus,
  AssociationProviderEventInputSchema as ProviderEventInputSchema,
  type AssociationProviderEventInput as ProviderEventInput,
  AssociationRegistrationStatusSchema as RegistrationStatusSchema,
  type AssociationRegistrationStatus as RegistrationStatus,
  AssociationRegistrationUpdateSchema as RegistrationUpdateSchema,
  type AssociationRegistrationUpdateInput as RegistrationUpdateInput,
  AssociationListPageSchema as ListPageSchema,
  associationFingerprint,
  mayTransitionAssociationOrder as mayTransitionOrder,
  mayTransitionAssociationRegistration as mayTransitionRegistration,
  type AssociationErrorCode,
  AssociationError,
} from '@use-brian/core'
