// @vitest-environment jsdom
import {act,type ReactNode} from "react";
import {createRoot,type Root} from "react-dom/client";
import {beforeEach,afterEach,describe,it,expect,vi} from "vitest";
const api=vi.hoisted(()=>({catalog:vi.fn(),resources:vi.fn(),create:vi.fn(),revoke:vi.fn(),list:vi.fn(),confirm:vi.fn()}));
vi.mock("@/lib/api/crm-administration",()=>({getCrmCredentialCatalog:api.catalog,getCrmScopeResources:api.resources,createCrmCredential:api.create,revokeCrmCredential:api.revoke}));
vi.mock("@/lib/api/association",()=>({listAssociationPage:api.list}));
vi.mock("@/components/ui/confirm-dialog",()=>({confirmDialog:api.confirm}));
vi.mock("@/lib/surface-prefetch",()=>({associationPageCacheKey:(w:string,r:string,q={})=>`crm:${w}:viewer:${r}:${JSON.stringify(q)}`,associationIntentKey:(w:string,op:string,target:string)=>`request:${w}:viewer:${op}:${target}`}));
import {AssociationCredentialForm,AssociationCredentialsPanel} from "../credentials-panel";
import {I18nProvider} from "@/lib/i18n/client";
import {en} from "@/lib/i18n/dictionaries/en";
import {resetSurfaceCache} from "@/lib/surface-cache";
const t=en.associationPage,a=t.admin;
const credential={id:"credential-old",label:"Fictional integration",prefix:"sk_crm_safe_prefix",expiresAt:"2028-01-01T00:00:00Z",revokedAt:null,createdAt:"2026-01-01T00:00:00Z",lastUsedAt:null,grants:[{operation:"association.read",selectors:{eventIds:["event-one"]}}]};
(globalThis as {IS_REACT_ACT_ENVIRONMENT?:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
let host:HTMLDivElement,root:Root;
async function render(node:ReactNode){await act(async()=>root.render(<I18nProvider locale="en" dict={en}>{node}</I18nProvider>));}
async function click(label:string){const b=[...host.querySelectorAll("button")].find(b=>b.textContent===label);expect(b,`Missing ${label}`).toBeTruthy();await act(async()=>b!.click());}
async function toggle(label:string){const l=[...host.querySelectorAll("label")].find(l=>l.textContent===label);const b=l?.querySelector('button,[role="checkbox"]');expect(b,`Missing toggle ${label}`).toBeTruthy();await act(async()=>{(b as HTMLElement).click();});}
async function field(label:string,value:string){const el=[...host.querySelectorAll("label")].find(l=>l.firstChild?.textContent===label)?.querySelector("input")!;expect(el).toBeTruthy();await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")!.set!.call(el,value);el.dispatchEvent(new Event("input",{bubbles:true}));});}
async function submit(){await act(async()=>{host.querySelector("form")!.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}));});}
async function setupForm(rotate=false){await render(<AssociationCredentialForm workspaceId="w" disabled={false} rotate={rotate?credential:undefined} onSaved={()=>{}}/>);await field(a.label,"Backend access");await field(a.expiry,"2028-01-01T00:00");await toggle("association.read");}
beforeEach(()=>{resetSurfaceCache();sessionStorage.clear();vi.resetAllMocks();api.catalog.mockResolvedValue({operations:["association.read","crm.records.read"],selectors:{"association.read":["eventIds"],"crm.records.read":[]}});api.resources.mockResolvedValue({eventIds:[{id:"event-one",label:"Workshop"}],planIds:[],definitionIds:[],purposeKeys:[]});api.confirm.mockResolvedValue(true);api.create.mockResolvedValue({...credential,oneTimeSecret:"fixture-secret-once"});api.list.mockResolvedValue({items:[credential],nextCursor:null});api.revoke.mockResolvedValue({revoked:true});host=document.createElement("div");document.body.appendChild(host);root=createRoot(host);});
afterEach(async()=>{await act(async()=>root.unmount());host.remove();resetSurfaceCache();});
describe("[COMP:app-web/association] Owner scoped-key administration",()=>{
  it("starts each permission without resource access and submits only explicitly selected ids",async()=>{await setupForm();expect(host.textContent).toContain(a.scopeHelp);await toggle("Workshop (event-one)");await submit();expect(api.create).toHaveBeenCalledWith("w",{label:"Backend access",expiresAt:new Date("2028-01-01T00:00").toISOString(),grants:[{operation:"association.read",selectors:{eventIds:["event-one"]}}]});});
  it("never infers all resources from an operation grant",async()=>{await setupForm();await submit();expect(api.create.mock.calls[0][1].grants).toEqual([{operation:"association.read",selectors:{}}]);});
  it("requires explicit all-resource selection and optional atomic rotation revocation",async()=>{await setupForm(true);await toggle(a.allResources);await toggle(a.revokeOld);await submit();expect(api.create.mock.calls[0][1]).toMatchObject({revokeCredentialId:credential.id,grants:[{operation:"association.read",selectors:{eventIds:"all"}}]});});
  it("shows the secret once in memory and stores only a random attempt reference",async()=>{await setupForm();await submit();expect(host.querySelector(`input[value="fixture-secret-once"]`)).not.toBeNull();expect(Object.values(sessionStorage)).toHaveLength(1);expect(Object.values(sessionStorage)[0]).toMatch(/^[a-f0-9-]{36}$/);await click(a.dismissSecret);expect(host.querySelector(`input[value="fixture-secret-once"]`)).toBeNull();expect(host.textContent).not.toContain("fixture-secret-once");await submit();expect(api.create).toHaveBeenCalledTimes(1);});
  it("retains uncertain-create admission across remount and cancelled review",async()=>{api.create.mockRejectedValueOnce(new Error("lost response"));await setupForm();await submit();expect(host.textContent).toContain(a.uncertainKey);await render(null);await render(<AssociationCredentialForm workspaceId="w" disabled={false} onSaved={()=>{}}/>);await submit();expect(api.create).toHaveBeenCalledTimes(1);api.confirm.mockResolvedValueOnce(false);await click(a.reviewNewKey);await submit();expect(api.create).toHaveBeenCalledTimes(1);await click(a.reviewNewKey);await field(a.label,"Backend access");await field(a.expiry,"2028-01-01T00:00");await toggle("association.read");await submit();expect(api.create).toHaveBeenCalledTimes(2);});
  it("blocks on owner denial/catalog failure without dispatching or storing a secret",async()=>{await render(<AssociationCredentialForm workspaceId="w" disabled onSaved={()=>{}}/>);await submit();expect(api.create).not.toHaveBeenCalled();await render(null);resetSurfaceCache();api.catalog.mockRejectedValue(new Error("403"));await render(<AssociationCredentialForm workspaceId="w" disabled={false} onSaved={()=>{}}/>);await submit();expect(api.create).not.toHaveBeenCalled();expect(host.textContent).toContain(t.manage.loadFailed);});
  it("revokes the exact selected credential after review and respects cancelled review",async()=>{await render(<AssociationCredentialsPanel workspaceId="w" disabled={false}/>);api.confirm.mockResolvedValueOnce(false);await click(a.revokeKey);expect(api.revoke).not.toHaveBeenCalled();await click(a.revokeKey);expect(api.revoke).toHaveBeenCalledExactlyOnceWith("w",credential.id);});
  it("follows all credential pages and keeps the last good page on failure",async()=>{api.list.mockImplementation(async(_w,_r,q)=>({items:[{...credential,id:q.cursor?"last-key":"first-key"}],nextCursor:q.cursor?null:"next-key"}));await render(<AssociationCredentialsPanel workspaceId="w" disabled={false}/>);await click(t.next);expect(api.list).toHaveBeenCalledWith("w","credentials",{cursor:"next-key"});expect(host.textContent).toContain("last-key");api.list.mockRejectedValue(new Error("offline"));await click(t.refresh);expect(host.textContent).toContain("last-key");expect(host.textContent).toContain(t.manage.loadFailed);});
});
