// @vitest-environment jsdom
import {act,type ReactNode} from "react";
import {createRoot,type Root} from "react-dom/client";
import {beforeEach,afterEach,describe,it,expect,vi} from "vitest";
const api=vi.hoisted(()=>({purposes:vi.fn(),savePolicy:vi.fn(),getGrant:vi.fn(),saveGrant:vi.fn(),confirm:vi.fn()}));
vi.mock("@/lib/api/crm",()=>({listCrmConsentPurposes:api.purposes}));
vi.mock("@/lib/api/crm-administration",()=>({saveCrmMailboxPolicy:api.savePolicy,getCrmMailboxGrant:api.getGrant,saveCrmMailboxGrant:api.saveGrant}));
vi.mock("@/lib/surface-prefetch",()=>({associationPageCacheKey:(w:string,r:string,q={})=>`crm:${w}:viewer:${r}:${JSON.stringify(q)}`}));
vi.mock("@/components/ui/confirm-dialog",()=>({confirmDialog:api.confirm}));
import {AssociationMailboxPolicyForm,AssociationMailboxGrantControl} from "../mailbox-panel";
import {I18nProvider} from "@/lib/i18n/client";
import {en} from "@/lib/i18n/dictionaries/en";
import {resetSurfaceCache,markSurfaceCacheStale} from "@/lib/surface-cache";
const t=en.associationPage,a=t.admin;
const policy={connectorInstanceId:"mailbox-one",providerKey:"outreach",version:4,managed:true,purposeKeys:["updates"],templatePurposes:{welcome:"updates"}};
const credential={id:"credential-one",label:"Fictional integration",prefix:"safe-prefix",expiresAt:"2028-01-01T00:00:00Z",revokedAt:null,createdAt:"2026-01-01T00:00:00Z",lastUsedAt:null,grants:[]};
let host:HTMLDivElement,root:Root;
(globalThis as {IS_REACT_ACT_ENVIRONMENT?:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
async function render(node:ReactNode){await act(async()=>root.render(<I18nProvider locale="en" dict={en}>{node}</I18nProvider>));}
async function toggle(label:string){const el=[...host.querySelectorAll("label")].find(l=>l.textContent===label)?.querySelector('[role="checkbox"]') as HTMLElement;expect(el).toBeTruthy();await act(async()=>el.click());}
async function submit(){await act(async()=>{host.querySelector("form")!.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}));});}
beforeEach(()=>{resetSurfaceCache();vi.resetAllMocks();api.confirm.mockResolvedValue(true);api.purposes.mockResolvedValue([{id:"purpose-one",purposeKey:"updates",label:"Updates",applicableChannels:["email"],archivedAt:null},{id:"purpose-two",purposeKey:"billing",label:"Billing",applicableChannels:["email"],archivedAt:null}]);api.savePolicy.mockResolvedValue({record:{...policy,version:5}});api.getGrant.mockResolvedValue({grant:{credentialId:credential.id,connectorInstanceId:"mailbox-one",version:2,enabled:false}});api.saveGrant.mockResolvedValue({});host=document.createElement("div");document.body.appendChild(host);root=createRoot(host);});
afterEach(async()=>{await act(async()=>root.unmount());host.remove();resetSurfaceCache();});
describe("[COMP:app-web/association] Managed-mailbox owner controls",()=>{
  it("confirms the displayed policy version and preserves template bindings",async()=>{await render(<AssociationMailboxPolicyForm workspaceId="w" instanceId="mailbox-one" policy={policy} disabled={false} onSaved={()=>{}}/>);await toggle("Billing (billing)");await submit();expect(api.savePolicy).toHaveBeenCalledWith("w","mailbox-one",{expectedVersion:4,confirmed:true,providerKey:"outreach",managed:true,purposeKeys:["updates","billing"],templatePurposes:{welcome:"updates"}});const field=[...host.querySelectorAll("input")].find(input=>input.value==="outreach");expect(field?.disabled).toBe(true);});
  it("leaves denied, cancelled and stale saves without a retry",async()=>{await render(<AssociationMailboxPolicyForm workspaceId="w" instanceId="mailbox-one" policy={policy} disabled onSaved={()=>{}}/>);await submit();expect(api.savePolicy).not.toHaveBeenCalled();await render(<AssociationMailboxPolicyForm workspaceId="w" instanceId="mailbox-one" policy={policy} disabled={false} onSaved={()=>{}}/>);api.confirm.mockResolvedValueOnce(false);await submit();expect(api.savePolicy).not.toHaveBeenCalled();api.savePolicy.mockRejectedValue(new Error("stale policy"));await submit();expect(api.savePolicy).toHaveBeenCalledTimes(1);expect(host.textContent).toContain(t.manage.failed);});
  it("cannot add an archived purpose and keeps failed catalog reads closed",async()=>{api.purposes.mockResolvedValue([{id:"one",purposeKey:"old",label:"Archived",applicableChannels:["email"],archivedAt:"2026-01-01"}]);await render(<AssociationMailboxPolicyForm workspaceId="w" instanceId="mailbox-one" policy={policy} disabled={false} onSaved={()=>{}}/>);const checkbox=[...host.querySelectorAll("label")].find(l=>l.textContent==="Archived (old)")?.querySelector('[role="checkbox"]') as HTMLButtonElement;expect(checkbox.hasAttribute("data-disabled")).toBe(true);api.purposes.mockRejectedValue(new Error("offline"));await act(async()=>markSurfaceCacheStale("crm:w:"));await submit();expect(api.savePolicy).not.toHaveBeenCalled();});
  it("binds only the selected credential and mailbox at their displayed version",async()=>{await render(<AssociationMailboxGrantControl workspaceId="w" instanceId="mailbox-one" credential={credential} disabled={false}/>);await toggle(a.allowMailbox);expect(api.saveGrant).toHaveBeenCalledExactlyOnceWith("w","mailbox-one",credential.id,{expectedVersion:2,confirmed:true,enabled:true});});
  it("allows revocation after credential expiry but cannot re-enable an expired credential",async()=>{api.getGrant.mockResolvedValue({grant:{version:3,enabled:true}});const expired={...credential,expiresAt:"2020-01-01T00:00:00Z"};await render(<AssociationMailboxGrantControl workspaceId="w" instanceId="mailbox-one" credential={expired} disabled={false}/>);api.getGrant.mockResolvedValue({grant:{version:4,enabled:false}});await toggle(a.allowMailbox);expect(api.saveGrant).toHaveBeenCalledWith("w","mailbox-one",credential.id,{expectedVersion:3,confirmed:true,enabled:false});const checkbox=host.querySelector('[role="checkbox"]') as HTMLButtonElement;expect(checkbox.hasAttribute("data-disabled")).toBe(true);await toggle(a.allowMailbox);expect(api.saveGrant).toHaveBeenCalledTimes(1);});
});
