/** Canonical CRM copy root predicates. [COMP:crm/privacy-copies] */
export const CRM_TASK_COPY_ROOT = "t.attributes->>'crm_contact_id'=$2::text OR EXISTS(SELECT 1 FROM association_enquiries q WHERE q.workspace_id=$1 AND (q.follow_up_task_id=t.id AND q.contact_id=$2)) OR EXISTS(SELECT 1 FROM entity_links l WHERE l.workspace_id=$1 AND ((l.source_kind='task' AND l.source_id::text=t.id::text AND l.target_kind IN('entity','contact','company','deal') AND l.target_id::text=$2::text) OR (l.target_kind='task' AND l.target_id::text=t.id::text AND l.source_kind IN('entity','contact','company','deal') AND l.source_id::text=$2::text))) OR EXISTS(SELECT 1 FROM association_enquiries q WHERE q.workspace_id=$1 AND q.id::text=t.attributes->>'crm_submission_id' AND q.contact_id=$2)"
export const CRM_SUBJECT_EMAILS = "SELECT lower(btrim(COALESCE(NULLIF(e.attributes->>'email',''),e.canonical_id))) FROM entities e WHERE e.workspace_id=$1 AND e.id=$2 AND COALESCE(NULLIF(e.attributes->>'email',''),e.canonical_id) IS NOT NULL UNION SELECT lower(btrim(i.normalized_value)) FROM entity_external_identities i WHERE i.workspace_id=$1 AND i.entity_id=$2 AND i.identity_kind='email'"

/** Alias is a server-owned SQL identifier, never client input. */
export function crmDraftHasSubjectRecipient(alias: 'd' | 'v'): string {
  return `EXISTS(SELECT 1 FROM unnest(${alias}.to_addresses||${alias}.cc_addresses||${alias}.bcc_addresses) a WHERE lower(btrim(a)) IN(${CRM_SUBJECT_EMAILS}))`
}

export const CRM_SHARED_TASK_ROOT = "(t.attributes->>'crm_contact_id' IS NOT NULL AND t.attributes->>'crm_contact_id'<>$2::text)\n      OR (t.attributes->>'crm_submission_id' IS NOT NULL AND (\n        EXISTS(SELECT 1 FROM association_enquiries q WHERE q.workspace_id=$1\n          AND q.id::text=t.attributes->>'crm_submission_id' AND q.contact_id<>$2)\n        OR (t.attributes->>'crm_contact_id' IS DISTINCT FROM $2::text\n          AND NOT EXISTS(SELECT 1 FROM association_enquiries q WHERE q.workspace_id=$1\n            AND q.id::text=t.attributes->>'crm_submission_id' AND q.contact_id=$2))))\n      OR EXISTS(SELECT 1 FROM association_enquiries q WHERE q.workspace_id=$1 AND q.follow_up_task_id=t.id AND q.contact_id<>$2)\n      OR EXISTS(SELECT 1 FROM entity_links l WHERE l.workspace_id=$1 AND (\n        (l.source_kind='task' AND l.source_id=t.id AND l.target_kind IN('entity','contact','company','deal') AND l.target_id<>$2)\n        OR (l.target_kind='task' AND l.target_id=t.id AND l.source_kind IN('entity','contact','company','deal') AND l.source_id<>$2)))"

/** Existing duplicate email identities make recipient ownership ambiguous. */
export const CRM_OTHER_CONTACT_EMAILS = "SELECT lower(btrim(COALESCE(NULLIF(e.attributes->>'email',''),e.canonical_id))) FROM entities e WHERE e.workspace_id=$1 AND e.id<>$2 AND e.kind='person' AND COALESCE(NULLIF(e.attributes->>'email',''),e.canonical_id) IS NOT NULL UNION SELECT lower(btrim(i.normalized_value)) FROM entity_external_identities i JOIN entities e ON e.workspace_id=i.workspace_id AND e.id=i.entity_id WHERE i.workspace_id=$1 AND i.entity_id<>$2 AND e.kind='person' AND i.identity_kind='email'"

/** Workspace scope follows CRM roots and the same dependent task closure. */
export const CRM_WORKSPACE_TASK_ROOT = "EXISTS(SELECT 1 FROM association_enquiries q WHERE q.workspace_id=$1 AND (q.follow_up_task_id=t.id)) OR EXISTS(SELECT 1 FROM entities e WHERE e.workspace_id=$1 AND (e.id::text=t.attributes->>'crm_contact_id' AND e.kind IN('person','company','deal'))) OR EXISTS(SELECT 1 FROM entities e WHERE e.workspace_id=$1 AND (e.kind IN('person','company','deal') AND EXISTS(SELECT 1 FROM entity_links l WHERE l.workspace_id=$1 AND ((l.source_kind='task' AND l.source_id::text=t.id::text AND l.target_kind IN('entity','contact','company','deal') AND l.target_id::text=e.id::text) OR (l.target_kind='task' AND l.target_id::text=t.id::text AND l.source_kind IN('entity','contact','company','deal') AND l.source_id::text=e.id::text))))) OR EXISTS(SELECT 1 FROM association_enquiries q WHERE q.workspace_id=$1 AND q.id::text=t.attributes->>'crm_submission_id')"
